aprs = { aprs_record? ~ ("\n" ~ aprs_record )* }
aprs_record = { aprs_corpus ~ comment? }
// TODO Find check names
aprs_corpus = ${ sender ~ ">" ~ receiver ~ ":/" ~ time ~ "h" ~ coordinates ~ track ~ "/" ~ speed ~ "/" ~ altitude }
sender = { ASCII_ALPHANUMERIC+ }
receiver = ${ receiver_field ~ ( "," ~ receiver_field )* }
receiver_field = { (ASCII_ALPHANUMERIC | "*")+ }

time = { digit{6} }
track = { digit{3} }
coordinates = ${ latitude ~ aprs_symbol ~ longitude ~ aprs_symbol }
latitude = ${ latitude_float ~ latitude_bearing }
longitude = ${ longitude_float ~ longitude_bearing }
latitude_float = ${ digit{4} ~ "." ~ digit{2} }
longitude_float = ${ digit{5} ~ "." ~ digit{2} }
latitude_bearing = { "N"|"S" }
longitude_bearing = { "E"|"W" }
coord_float = @{ digit{4} ~ "." ~ digit{2} }
speed = { digit{3} }
altitude = !{ "A=" ~ digit+ }
aprs_symbol = { ASCII }

comment = { comment_field* }
id = @{ "id" ~ ASCII_ALPHANUMERIC+ }
comment_field = _{ id | climb_rate | turning_rate | flight_level | frequency | w_field | unknown_option }
climb_rate = !{ number_with_sign ~ "fpm" }
turning_rate = !{ number_with_sign ~ "rot" }
flight_level = !{ "FL" ~ float }
horizontal_accuracy = { integer }
vertical_accuracy = { integer }
frequency = { number_with_sign ~ "kHz" }
signal_strength = { number ~ "dB" }
sign = {"+" | "-"}
w_field = { "!" ~ "W" ~ digit+ ~ "!" }
unknown_option = { ASCII+ }

digit = _{ ASCII_DIGIT }
number_with_sign = @{ sign ~ number }
number = @{ digit+ ~ ( "." ~ integer )? }
integer = _{ digit+ }
float = @{ integer ~ "." ~ integer }
WHITESPACE = _{ " "+ }
