[package]
name = "aprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
chrono = "0.4.22"
dms-coordinates = "1.1"
geo = "0.23"
itertools = "0.11.0"
log = "0.4"
pest = "2.4"
pest_derive = "2.4"

[dev-dependencies]
float_eq = "1.0"
